### PR TITLE
Pause the wallpaper when active windows are max

### PR DESCRIPTION
**Pull request by Semidio**

### CODE REVIEW

**Comment by SegoCode** [comment]
I thought it a lot when I implemented it, the animation to minimize window is very fast and you will see the wallpaper stopped for two seconds, I guess a configuration for this will be implemented, I personally prefer not to see it stopped.
what do you think?

**Comment by Semidio** [comment]
Make this function optional is a great idea, maybe it can set sleep to 500 or even lower, this will not add any stress on cpu.

**Comment by SegoCode** [comment]
Yes, but i'm afraid that Autoit use and stress other Windows services to check that and add some system instability, that is the reason why i put Sleep(2000).... I will monitor the system to see how impact in the performance

**Comment by SegoCode** [comment]
Well, i tested a lot and i dont find any stability problems. But your version its so tricky so i made this, most simple ;
```autoit
#include <Misc.au3>
#include <AutoItConstants.au3>
While 1
    $Actwin = WinGetHandle("[active]")
    If BitAND(WinGetState($Actwin), $WIN_STATE_MAXIMIZED) Then
	MsgBox(0, "Result", "Active window is maximized")
    Else
        MsgBox(0, "Result",  "Active window dont fit full screen")
    EndIf
    Sleep(5000)
WEnd
```
And the implementation in autoPause.au3 it's as simple, adding this ` Or BitAND(WinGetState($Actwin), $WIN_STATE_MAXIMIZED)` to actual checking 

Any way thx a lot for your contribution and support 💕

**Pull request closed without merging**
